version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-intl
    versions:
    - 5.10.16
    - 5.11.0
    - 5.12.1
    - 5.12.3
    - 5.12.5
    - 5.13.1
    - 5.13.2
    - 5.13.5
    - 5.15.3
    - 5.15.7
    - 5.15.8
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mdi-material-ui
    versions:
    - 6.21.0
    - 6.22.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
