language: node_js
node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      script: skip
      before_deploy:
        - yarn build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        target_branch: master
        local_dir: build
        on:
          branch: source
